# Generated by Django 3.2.25 on 2024-08-06 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20240806_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='day',
        ),
    ]
