# Generated by Django 3.2.25 on 2024-08-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20240806_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='session',
            name='start_time',
        ),
        migrations.AddField(
            model_name='session',
            name='duration',
            field=models.CharField(default='3:00 PM - 3:30 PM', max_length=50),
        ),
    ]
