# Generated by Django 3.2.25 on 2024-08-06 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_session_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
    ]
